### ISSUE TITLE
How to run train_fol.py using the provided features(pkl files in train folder)

### ISSUE THREAD

**Issue by ltzhuchen** [MoonBlvd/tad-IROS2019#12]
Could you pls let us know which config is available or how to revise the config to use the downloaded features to train fol. When I use the existing fol_ego_train.yaml, it failed to find the best_ego_pred_model. Thanks in advance

**Comment by MoonBlvd** [comment]
Hi,

It cannot find ```best_ego_pred_model``` because you don't have that pre-trained weight file. You have two options: 1) train the ego_pred model by yourself and use the saved checkpoint; 2) remove the checkpoint loading code in the training script to train the whole model from random initialization. 

Thank you,
Brian

**Comment by ltzhuchen** [comment]
Thank you for your kind reply.
It seems I have figured it out by changing line 140 of fol_dataloader.py to "ego_motion_session = torch.FloatTensor(ego_motion_session['ego_motion'])" and corresponding path of train/val data. Then we can use "python train_ego_pred.py --load_config config/fol_ego_train.yaml" to run the training. BTW there is no fvl_dataloader, I have changed it to fol_dataloader. 
For anyone who my need it.

**Comment by MoonBlvd** [comment]
@ltzhuchen Glad to know that you got it work! And thank you for correcting the name of the file. The "fvl" was a typo and it should be "fol" as you said.
