### ISSUE TITLE
Train ego_pred on DoTA dataset.

### ISSUE THREAD

**Issue by varunjammula** [MoonBlvd/tad-IROS2019#15]
Hi, I would like to train the ego prediction using on DoTA dataset. Do you have suggestions on how to do that? Thanks.

**Comment by MoonBlvd** [comment]
Hi@varunjammula, the only way to get ego motion data from DoTA I can come up with immediately is to use a visual odometry. FYI, I have used ORB-SLAM2 for A3D data, but have not tried DoTA

**Comment by varunjammula** [comment]
Ok, thanks. Will try and update the issue.

**Comment by MoonBlvd** [comment]
Hi @varunjammula Can you please close this issue if problem is solved? Thanks!
