### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by brinst07** [MoonBlvd/tad-IROS2019#17]
Hi thank you for sharing this code
i tried ```python train_ego_pred.py --load_config config/fol_ego_train.yaml``` but it cause this error
![image](https://user-images.githubusercontent.com/60083557/88768654-5a739a00-d1b6-11ea-98b7-ca8f7bac0749.png)

plz help me

**Comment by MoonBlvd** [comment]
Hi @brinst07 it seems to be a issue with pytorch sampler function, can you check if the dataset you sample from is not empty?

**Comment by MoonBlvd** [comment]
Hi @brinst07  is your problem solved? If so, could you please close this issue?

**Comment by brinst07** [comment]
thank you ^^
