### ISSUE TITLE
The tracking result of deep_sort.

### ISSUE THREAD

**Issue by Flawless1202** [MoonBlvd/tad-IROS2019#2]
I find that the tracking results getting from `deep_sort` are not always continuous. But these in the features provided by you are continuous. So have you done the linear interpolation? @MoonBlvd

**Comment by MoonBlvd** [comment]
Hi @Flawless1202  deep_sort is not always continuous. What I did in the ICRA paper was to select tracklets that are longer than 20 frames (2seconds) because the input was 10 frames and the prediction horizon was 10frames as well. I didn't do any interpolation at that point.

**Comment by Flawless1202** [comment]
@MoonBlvd  Thanks for your reply!
