### ISSUE TITLE
A3D, DoTA features

### ISSUE THREAD

**Issue by hwk0702** [MoonBlvd/tad-IROS2019#20]
I trained the model using the HEV-I features data you published.
A3D and DoTA data need to generate features with FlowNet or ORBSLAM the same as HEV-I data?
If so, can i get a code that creates a feature using FlowNet or ORBSLAM?
Thank you.

**Comment by MoonBlvd** [comment]
@hwk0702  The readme file already provides links to these modules we used. Please check them out.
