### ISSUE TITLE
Unresolved reference 'OUT_DIR'

### ISSUE THREAD

**Issue by justanewcomer233** [MoonBlvd/tad-IROS2019#28]
hi，author,thanks for your job first.I noticed a small problem while looking at the code
'save_dir = os.path.join(OUT_DIR, video_name)' in run_fol_for_AD.py,PyCharm prompts Unresolved reference 'OUT_DIR'.I don't know what the problem is.Please help me.

**Comment by justanewcomer233** [comment]
And in eval_utils.py : traj = bbox[:,:2], pycharm prompt Unresolved reference 'bbox'

**Comment by MoonBlvd** [comment]
Hi @justanewcomer233 , thank you for your interest in our work. 

1) you can indicate OUT_DIR to be whatever directory you want to save your output at the begining of this file.
2) sorry for the confusion, this function should not be used in the code so you can ignore it.

**Comment by justanewcomer233** [comment]
thanks for your answer
