### ISSUE TITLE
A3D_urls.txt links are dead.

### ISSUE THREAD

**Issue by ynalcakan** [MoonBlvd/tad-IROS2019#31]
Given links in A3D_urls.txt file are dead.

**Comment by MindsetFather** [comment]
I had the same problem and asked for help

**Comment by MoonBlvd** [comment]
Hi, thank you for your interest in our work and sorry for the late response. We had a newer paper which expanded the A3D data set to a ~5000 video DoTA dataset: https://github.com/MoonBlvd/Detection-of-Traffic-Anomaly
