### ISSUE TITLE
The `predict` method of `FolRNNED` class

### ISSUE THREAD

**Issue by Flawless1202** [MoonBlvd/tad-IROS2019#4]
@MoonBlvd  Is the `predict` method of `FolRNNED` class cooresponding to the *Bounding Box Prediction* subsection in the article *Unsupervised Traffic Accident Detection in First-Person Videos* ? Does it work well?

**Comment by Flawless1202** [comment]
I am doing my final project and looking forward to your reply soon. Thanks a lot! @MoonBlvd

**Comment by MoonBlvd** [comment]
I think the ```predict``` method of FolRNNED was not used. I left it there for future use.
