### ISSUE TITLE
Is the A3D dataset available now?

### ISSUE THREAD

**Issue by Flawless1202** [MoonBlvd/tad-IROS2019#5]

**Comment by MoonBlvd** [comment]
Yes! Please give us one or two weeks to set up the website and liscenses.

**Comment by Flawless1202** [comment]
Thanks a lot! @MoonBlvd

**Comment by MoonBlvd** [comment]
@Flawless1202
This repo has been updated and the dataset is provided!

**Comment by Flawless1202** [comment]
OK! Thanks a lot!
